name: Deploy Nuxt 3 App
on:
  push:
    branches:
      - master
    # paths-ignore:
    #   - "./github/workflows/*"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: yarn install
      - name: Build application
        run: yarn run build
  lint:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: yarn install
      # - name: Lint application
      #   run: yarn run lint
  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: yarn install
      - name: Build application
        run: yarn run build
      - name: Deploy application
        run: echo Deploying ...
